# Generated by Django 5.2.7 on 2025-10-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('order-inquiry', 'Order Inquiry'), ('product-question', 'Product Question'), ('shipping-info', 'Shipping Information'), ('return-exchange', 'Return & Exchange'), ('wholesale', 'Wholesale Inquiry'), ('collaboration', 'Collaboration'), ('complaint', 'Complaint'), ('other', 'Other')], max_length=50)),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('newsletter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
